### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by litvinkaa** [CrazyYKROP/engineering_lab1#1]
C++ features like Input/Output operators and libraries like IPP can be used to further improve performance.
Also would be good to validate input data.
read_input_file function can be improved to handle atypical cases without failing (for example, a 'space' among the numbers in a row)
A good idea would be to create test cases that include all possible variants (wins with different configuration of consecutive stones, draws etc).

**Comment by CrazyYKROP** [comment]
Using IPP will not bring enchantments this lib being most for math operation. Other steps done in pull request
