### ISSUE TITLE
Introduce new type

### ISSUE THREAD

**Issue by IanaKhitsko** [CrazyYKROP/engineering_lab1#3]
https://github.com/CrazyYKROP/engineering_lab1/blob/45827636a312146752029005d3cfce2854bfa0e9/main.cpp#L18

Please introduce new type for std::vector<std::vector<>> - the code will be more readable

**Comment by CrazyYKROP** [comment]
https://github.com/CrazyYKROP/engineering_lab1/blob/6676a4fd33fb52abfc92289f9782d7f5dce9a81c/main.cpp#L12

New type alias introduced
