### ISSUE TITLE
Early return

### ISSUE THREAD

**Issue by IanaKhitsko** [CrazyYKROP/engineering_lab1#4]
https://github.com/CrazyYKROP/engineering_lab1/blob/45827636a312146752029005d3cfce2854bfa0e9/main.cpp#L43

introduce early return to make the cycle body more aligned 

if (board[i][j] == 0) continue;
...

**Comment by CrazyYKROP** [comment]
https://github.com/CrazyYKROP/engineering_lab1/blob/6676a4fd33fb52abfc92289f9782d7f5dce9a81c/main.cpp#L116-L121

https://github.com/CrazyYKROP/engineering_lab1/blob/6676a4fd33fb52abfc92289f9782d7f5dce9a81c/main.cpp#L134-L135

Introduced skipping and parse validation to skip not valid boards
