### ISSUE TITLE
const for 5

### ISSUE THREAD

**Issue by IanaKhitsko** [CrazyYKROP/engineering_lab1#5]
https://github.com/CrazyYKROP/engineering_lab1/blob/45827636a312146752029005d3cfce2854bfa0e9/main.cpp#L59

introduce const for 5

**Comment by CrazyYKROP** [comment]
https://github.com/CrazyYKROP/engineering_lab1/blob/6676a4fd33fb52abfc92289f9782d7f5dce9a81c/main.cpp#L44

Inroduced 5 as const MAX_COMBO
