### ISSUE TITLE
line bounds

### ISSUE THREAD

**Issue by IanaKhitsko** [CrazyYKROP/engineering_lab1#6]
https://github.com/CrazyYKROP/engineering_lab1/blob/45827636a312146752029005d3cfce2854bfa0e9/main.cpp#L28

what if the actual line bounds are less than width?

**Comment by CrazyYKROP** [comment]
https://github.com/CrazyYKROP/engineering_lab1/blob/6676a4fd33fb52abfc92289f9782d7f5dce9a81c/main.cpp#L117-L130

https://github.com/CrazyYKROP/engineering_lab1/blob/6676a4fd33fb52abfc92289f9782d7f5dce9a81c/main.cpp#L134-L135

Board size is validated on level of parsing file. Not valid boards isn`t passed for processing
